### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by braver** [bcomnes/sublime-tron-color-scheme#4]
> Caveats
These themes have poor support for basic markdown currently. 

I would love to hear how [MarkdownHighlighting](https://packagecontrol.io/packages/MarkdownHighlighting) works for you in this color scheme!

**Comment by bcomnes** [comment]
The work around I use is to install https://github.com/jonschlinkert/sublime-monokai-extended and set markdown files to use that color scheme instead. See https://github.com/bcomnes/sublime-text-settings/blob/master/Packages/User/Markdown%20Extended.sublime-settings for an example of how this is done. I also do something similar for Json. See that second repo for that as well.

It would be great to improve the highlight support though.  I'm hoping someone who knows how just PRs it, but maybe one day I'll get around to it.

**Comment by bcomnes** [comment]
I totally misread your issue the other day.  I was on the bus!  lol  Sorry about that.  

MarkdownHighlighting looks totally awesome, I'm going to try it out and update the caveats section.

**Comment by braver** [comment]
No worries, stuff happens 👍🏻

**Comment by bcomnes** [comment]
@braver So I just tried it out, and its an improvement, but still does't shape this theme into the excellent shape that markdown extended achieves. I'm going to mention it in the README, but it looks like there is still some work to do.  

<img width="1392" alt="screen shot 2016-03-03 at 9 25 00 am" src="https://cloud.githubusercontent.com/assets/166301/13502956/f9bc6c84-e121-11e5-8602-b84d019d1250.png">
<img width="1392" alt="screen shot 2016-03-03 at 9 25 44 am" src="https://cloud.githubusercontent.com/assets/166301/13502958/fcbbf800-e121-11e5-99eb-99e38fe36b4a.png">

**Comment by braver** [comment]
It's not intended to match that, but provide something useable without having to use a color scheme for just one language. Glad you like it, and I'll look into adding some more features!

**Comment by bcomnes** [comment]
I'm interested in, at some point, porting over the extended features.  Ideally that work could land in a  generalized solution like MarkdownHighlighting, rather than just on set of themes.  I'm not sure if there are weird hacks or other limitations involved with the extended themes however.

**Comment by braver** [comment]
> I'm not sure if there are weird hacks or other limitations involved with the extended themes however.

No, it's usually just finding specific color combinations for each language. Especially markdown uses scopes like `markup.heading.1.markdown` that simply don't occur anywhere else and that most color schemes don't use. You can write a pretty good generic color scheme in a few hundred lines: the Dayle Rees schemes are about 700 lines, whereas Monokai Extended is over 1700.
